require 'rails_helper'

RSpec.describe CountryFacade do
  describe '#random' do
    it 'returns the name of a country at random', :vcr do
      countries = ['Gambia',
                   'Åland Islands',
                   'Cape Verde',
                   'Turkmenistan',
                   'Qatar',
                   'El Salvador',
                   'Georgia',
                   'Equatorial Guinea',
                   'Ivory Coast',
                   'Bahrain',
                   'Finland',
                   'Libya',
                   'Western Sahara',
                   'Ethiopia',
                   'Northern Mariana Islands',
                   'Bouvet Island',
                   'South Sudan',
                   'Mayotte',
                   'Palestine',
                   'Turks and Caicos Islands',
                   'Kyrgyzstan',
                   'Maldives',
                   'Bangladesh',
                   'American Samoa',
                   'Croatia',
                   'Cayman Islands',
                   'Afghanistan',
                   'Haiti',
                   'Antigua and Barbuda',
                   'Venezuela',
                   'Ireland',
                   'Canada',
                   'Saint Vincent and the Grenadines',
                   'Paraguay',
                   'Tuvalu',
                   'Mali',
                   'Austria',
                   'Myanmar',
                   'Benin',
                   'Cuba',
                   'Bahamas',
                   'United States Virgin Islands',
                   'Ukraine',
                   'Aruba',
                   'Switzerland',
                   'Liechtenstein',
                   'Comoros',
                   'Syria',
                   'Brunei',
                   'Curaçao',
                   'Guernsey',
                   'Liberia',
                   'Japan',
                   'Samoa',
                   'Solomon Islands',
                   'Central African Republic',
                   'Italy',
                   'Réunion',
                   'Togo',
                   'Tunisia',
                   'Taiwan',
                   'DR Congo',
                   'Mexico',
                   'Laos',
                   'Namibia',
                   'Saudi Arabia',
                   'Faroe Islands',
                   'Greece',
                   'Niger',
                   'Hong Kong',
                   'Cameroon',
                   'Suriname',
                   'Ecuador',
                   'Russia',
                   'Dominica',
                   'Monaco',
                   'Mozambique',
                   'Kosovo',
                   'Iraq',
                   'Montenegro',
                   'Saint Barthélemy',
                   'Mongolia',
                   'Chad',
                   'British Virgin Islands',
                   'Kenya',
                   'Cambodia',
                   'Portugal',
                   'Somalia',
                   'Falkland Islands',
                   'Pitcairn Islands',
                   'Nicaragua',
                   'Sri Lanka',
                   'Norway',
                   'Martinique',
                   'Seychelles',
                   'Madagascar',
                   'New Zealand',
                   'Saint Kitts and Nevis',
                   'Niue',
                   'Timor-Leste',
                   'Pakistan',
                   'Czechia',
                   'Wallis and Futuna',
                   'Tanzania',
                   'São Tomé and Príncipe',
                   'Israel',
                   'Bhutan',
                   'Albania',
                   'Bolivia',
                   'Cyprus',
                   'Guatemala',
                   'Saint Martin',
                   'Lithuania',
                   'Hungary',
                   'Senegal',
                   'Thailand',
                   'French Polynesia',
                   'Tajikistan',
                   'Bosnia and Herzegovina',
                   'Sudan',
                   'Poland',
                   'Marshall Islands',
                   'French Southern and Antarctic Lands',
                   'Jersey',
                   'Honduras',
                   'Macau',
                   'Montserrat',
                   'Christmas Island',
                   'Netherlands',
                   'Costa Rica',
                   'Micronesia',
                   'Kiribati',
                   'Greenland',
                   'Antarctica',
                   'Nigeria',
                   'Slovenia',
                   'Djibouti',
                   'Iran',
                   'Turkey',
                   'Papua New Guinea',
                   'Botswana',
                   'United States',
                   'South Korea',
                   'Algeria',
                   'Gabon',
                   'Romania',
                   'Vanuatu',
                   'Dominican Republic',
                   'Palau',
                   'Saint Pierre and Miquelon',
                   'India',
                   'Lesotho',
                   'New Caledonia',
                   'Latvia',
                   'Brazil',
                   'Morocco',
                   'Rwanda',
                   'Isle of Man',
                   'Bermuda',
                   'Mauritius',
                   'Sint Maarten',
                   'Yemen',
                   'France',
                   'Moldova',
                   'Uzbekistan',
                   'Cocos (Keeling) Islands',
                   'Nauru',
                   'Uganda',
                   'Republic of the Congo',
                   'Colombia',
                   'Puerto Rico',
                   'Kazakhstan',
                   'Estonia',
                   'Bulgaria',
                   'Heard Island and McDonald Islands',
                   'Tokelau',
                   'Belize',
                   'United States Minor Outlying Islands',
                   'United Arab Emirates',
                   'Peru',
                   'Oman',
                   'South Georgia',
                   'Sweden',
                   'Uruguay',
                   'South Africa',
                   'Malta',
                   'Belarus',
                   'Tonga',
                   'Cook Islands',
                   'Nepal',
                   'Vatican City',
                   'Barbados',
                   'Slovakia',
                   'French Guiana',
                   'North Macedonia',
                   'Germany',
                   'Andorra',
                   'Guam',
                   'Philippines',
                   'Burundi',
                   'Guyana',
                   'Svalbard and Jan Mayen',
                   'Burkina Faso',
                   'Zambia',
                   'Sierra Leone',
                   'United Kingdom',
                   'Anguilla',
                   'Guadeloupe',
                   'Lebanon',
                   'Iceland',
                   'Jordan',
                   'Norfolk Island',
                   'Jamaica',
                   'Singapore',
                   'Mauritania',
                   'Saint Helena, Ascension and Tristan da Cunha',
                   'Guinea-Bissau',
                   'Malaysia',
                   'Guinea',
                   'Grenada',
                   'Luxembourg',
                   'Malawi',
                   'Vietnam',
                   'Australia',
                   'Egypt',
                   'Zimbabwe',
                   'Indonesia',
                   'San Marino',
                   'Angola',
                   'North Korea',
                   'Fiji',
                   'Ghana',
                   'Denmark',
                   'Eritrea',
                   'Armenia',
                   'Chile',
                   'Trinidad and Tobago',
                   'Argentina',
                   'Kuwait',
                   'Saint Lucia',
                   'Caribbean Netherlands',
                   'Gibraltar',
                   'Panama',
                   'China',
                   'Eswatini',
                   'Spain',
                   'Azerbaijan',
                   'Belgium',
                   'Serbia',
                   'British Indian Ocean Territory']
      name = CountryFacade.random

      expect(name).to be_a String
      expect(countries.include?(name)).to be true
    end
  end
end
